package kr.jm.feature_search

import kr.jm.domain.model.SubwayStation

data class SearchScreenState(
    val allStations: List<SubwayStation> = emptyList(),
    val filteredStations: List<SubwayStation> = emptyList(),
    val selectedLineName: String = "",
    val subwayLineList: List<String> = listOf(
        "전체",
        "1호선",
        "2호선",
        "3호선",
        "4호선",
        "5호선",
        "6호선",
        "7호선",
        "7호선(인천)",
        "8호선",
        "9호선",
        "9호선(연장)",
        "공항철도1호선",
        "경의중앙선",
        "경춘선",
        "수인선",
        "분당선",
        "신분당선",
        "신분당선(연장)",
        "신분당선(연장2)",
        "경강선",
        "서해선",
        "인천1호선",
        "인천2호선",
        "에버라인선",
        "의정부선",
        "우이신설선",
        "김포골드라인",
        "신림선",
        "장항선",
        "경원선",
        "경부선",
        "중앙선",
        "일산선",
        "안산선",
        "경인선",
        "과천선",
        "진접선"
    ),
    val searchQuery: String = "",
    val dropDownExpanded: Boolean = false,
    val isLoading: Boolean = false,
    val errorMessage: String? = null
)
